"use client"
import type { Metadata } from "next"
import "./globals.css"
import Navbar from "@/components/ui/Navbar/Navbar"
import { Toaster } from "react-hot-toast";
import Footer from "@/components/ui/Footer/Footer";
import { SessionProvider } from "next-auth/react";


//export const metadata: Metadata = {
  //title: "A Mart",
  //description: "Generated by create next app",
//}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
      <html lang="en">
        <body>
                    <SessionProvider>

        
          <Navbar />
          <div className="">
            <Toaster/>
            {children}
          </div>
          <Footer/>
            </SessionProvider>
        </body>
      </html>
  )
}
