"use client"
import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.css"
import Navbar from "@/components/ui/Navbar/Navbar"
import { Toaster } from "react-hot-toast";
import Footer from "@/components/ui/Footer/Footer";
import { SessionProvider } from "next-auth/react";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
})

//export const metadata: Metadata = {
//title: "A Mart",
//description: "Generated by create next app",
//}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className="scroll-smooth">
      <body className={`${inter.className} antialiased`}>
        <SessionProvider>


          <Navbar />
          <div className="">
            <Toaster
              position="top-center"
              toastOptions={{
                style: {
                  borderRadius: '12px',
                  background: '#1a1a2e',
                  color: '#fff',
                  fontSize: '14px',
                  padding: '12px 20px',
                },
              }}
            />
            {children}
          </div>
          <Footer />
        </SessionProvider>
      </body>
    </html>
  )
}
